<?php namespace ProcessWire;

class IndividualSelectablePages extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Individual Selectable Pages',
			'summary' => 'Adds an option to the config of Page Reference fields that lets you define individual selectable pages via PageListSelectMultiple.',
			'version' => '0.1.0',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/IndividualSelectablePages',
			'icon' => 'check-square-o',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.0, PHP>=5.4.0',
		);
	}


	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookAfter('InputfieldPage::getConfigInputfields', $this, 'afterGetConfigInputfields');
	}

	/**
	 * Modify config inputfields for InputfieldPage 
	 *
	 * @param HookEvent $event
	 */
	protected function afterGetConfigInputfields(HookEvent $event) {
		/** @var InputfieldWrapper $wrapper */
		$wrapper = $event->return;
		$modules = $event->wire('modules');
		$if_selector_string = $wrapper->getChildByName('findPagesSelector');
		if(!$if_selector_string) return;

		// Get Individual Pages value if any
		$selector_string = $if_selector_string->value;
		$start_pos = strpos($selector_string, 'id=');
		if($start_pos !== false && strpos($selector_string, ',') === false) {
			$ids_str = substr($selector_string, $start_pos + 3);
			$value = $this->wire('sanitizer')->intArray($ids_str);
		} else {
			$value = [];
		}

		// Add Individual Pages inputfield
		/** @var InputfieldPageListSelectMultiple $f */
		$f = $modules->get('InputfieldPageListSelectMultiple');
		$f->name = '_individual_pages';
		$f->label = $this->_('Individual pages');
		$f->icon = 'check-square-o';
		$f->value = $value;
		$f->collapsed = Inputfield::collapsedBlank;
		$wrapper->insertAfter($f, $if_selector_string);

		// Add JS
		$config = $this->wire('config');
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->scripts->add($config->urls->$this . "{$this}.js?v=$version");
	}

}
